[build]
target = "thumbv6m-none-eabi"

[target.thumbv6m-none-eabi]
runner = "elf2uf2-rs --deploy --serial"

rustflags = [
    "-C", "link-arg=--nmagic",
    "-C", "link-arg=-Tlink.x",
    "-C", "linker=flip-link",
    # -Tdefmt.x NO incluido: no usamos defmt sin probe SWD
]